config = {
    "model":          "Autoformer",
    "seq_len":        336,
    "label_len":      48,
    "e_layers":       2,
    "d_layers":       1,
    "d_model":        512,
    "d_ff":           2048,
    "n_heads":        8,
    "factor":         1,
    "moving_avg":     25,
    "dropout":        0.05,
    "activation":     "gelu",
    "embed":          "timeF",
    "freq":           "h",
    "features":       "M",
    "patch_len":      16,

    "learning_rate":  0.0001,
    "train_epochs":   10,
    "epochs_forecasting": 10,
    "batch_size":     32,
    "batch_size_forecast": 32,
    "patience":       3,
    "num_workers":    4,
    "lradj":          "TST",
    "pct_start":      0.2,
    "loss":           "MSE",
    "drop_last":      True,
}
